name: Abilities
version: 1.0.0
main: de.tmxx.abilities.AbilitiesPlugin
author: tmxx
description: Abilities test plugin
api-version: 1.21
depend: [ProtocolLib]
libraries:
  - com.google.inject:guice:7.0.0
  - com.google.inject.extensions:guice-assistedinject:7.0.0